# Site settings
title: Ashes Blog
email: ashes.sqy126@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 欢迎访问我的博客，本博客记录了一个web开发小白的漫漫心路...
baseurl: "/myblog"  # the subpath of your site, e.g. /blog/
url: "http://ashessqy126.github.io/" # the base hostname & protocol for your site

github_username: ashessqy126

# Build settings
markdown: kramdown
